export PATH="$PATH:/opt"

# load environment variables
[[ -s "~/.config/shell/env.sh" ]] && source ~/.config/shell/env.sh
# source functions for zsh shell
[[ -s "~/.config/shell/functions.sh" ]] && source ~/.config/shell/functions.sh
# work file contains anything used for professional dev
[[ -s "~/.config/shell/work.sh" ]] && source ~/.config/shell/work.sh

# enable vim keybindings (terminal starts in insert mode)
bindkey -v

# source autosuggestions file
# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md#manual-git-clone
source ~/.local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# make zsh compdump XDG compliant
compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION

# advanced zsh settings
# https://gist.github.com/LukeSmithxyz/e62f26e55ea8b0ed41a65912fbebbe52

# history settings:
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE="$XDG_STATE_HOME/zsh/.zsh_history"
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS

# basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select # this causes weird side-effects?
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# set omp theme - https://ohmyposh.dev/docs/installation/customize
if [ -x "$(command -v oh-my-posh)" ]; then
	eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/.poshthemes/fish.omp.json)"
fi

# initialize asdf
# https://asdf-vm.com/guide/getting-started.html#_3-install-asdf
if [ -x "$(command -v asdf)" ]; then
	. "$XDG_DATA_HOME/asdf/asdf.sh"
fi

# initialize atuin
# https://github.com/atuinsh/atuin?tab=readme-ov-file#shell-plugin
if [ -x "$(command -v atuin)" ]; then
	eval "$(atuin init zsh)"
fi

# initialize mcfly
if [ -x "$command -v mcfly)" ]; then
	eval "$(mcfly init zsh)"
fi

# initialize git-forgit
#. "$XDG_DATA_HOME/forgit/bin/g"

# auto-generated by fzf install script
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh ] && source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh
